### PR TITLE
fixed SIP2-83: Allow checkout with externalUserId

### PR DESCRIPTION
**Pull request by shanghai-library**
fixed SIP2-83

### CODE REVIEW

**Comment by shanghai-library** [comment]
SIP2-83
Allow checkout witj externalUserId

**Comment by shanghai-library** [comment]
build faild is caused by checkstyle

**Comment by mreno-EBSCO** [comment]
I agree, @mtraneis. Instead of adding another user lookup here, we could just do all this in `PasswordVerifier.verifyPatronPassword()`. There already is a UsersRepository there and we retrieve the user. We could just move the `isPatronPasswordVerificationRequired()` inside the FOLIO response and always return a user, assuming no FOLIO errors. Although, I am not thrilled that user retrieval is a side effect of password verification. 🤷‍♂️ 

We should also consider other code that needs to do password verification and may possibly need the user retrieved from FOLIO. If we do a user lookup all the time in `PasswordVerifier`, then `PatronRepository` will no longer need the additional user lookup: https://github.com/folio-org/edge-sip2/blob/f7cb4298cdf7dcf301558b2c35c30039c92fbe64/src/main/java/org/folio/edge/sip2/repositories/PatronRepository.java#L104. There may or may not be other cases.

Also, please do not reorder/wildcard the import statements. This project uses Google's style and your editor needs to conform to that. https://google.github.io/styleguide/javaguide.html#s3.3-import-statements

**Comment by shanghai-library** [comment]
fixed SIP2-83 :revert CirculationRepository and CirculationRepositoryTests 
add getUserById in PasswordVerifier and delete PatronRepository: userFuture = usersRepository.getUserById(patronIdentifier, sessionData);

**Comment by mreno-EBSCO** [comment]
Could this code smell be corrected?
https://sonarcloud.io/project/issues?id=org.folio%3Aedge-sip2&pullRequest=46&resolved=false&types=CODE_SMELL

**Pull request merged**
